"""reports_roles_and_visibility

Revision ID: ba8207091fd0
Revises: 2f07ec09edfe
Create Date: 2026-09-05 14:53:04.286333

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ba8207091fd0"
down_revision: str | Sequence[str] | None = "2f07ec09edfe"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "report",
        sa.Column(
            "report_id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False
        ),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "content_last_modified_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("report_id", name=op.f("pk_report")),
    )
    op.create_table(
        "report_role",
        sa.Column("role", sa.Text(), nullable=False),
        sa.Column("precedence", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "precedence > 0", name=op.f("ck_report_role_precedence_positive")
        ),
        sa.PrimaryKeyConstraint("role", name=op.f("pk_report_role")),
        sa.UniqueConstraint("precedence", name=op.f("uq_report_role_precedence")),
    )
    op.create_table(
        "report_role_ledger",
        sa.Column("report_id", sa.UUID(), nullable=False),
        sa.Column("granted_to_user_id", sa.UUID(), nullable=False),
        sa.Column("set_by_user_id", sa.UUID(), nullable=False),
        sa.Column("role", sa.Text(), nullable=False),
        sa.Column(
            "set_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["granted_to_user_id"],
            ["app_user.user_id"],
            name=op.f("fk_report_role_ledger_granted_to_user_id_app_user"),
        ),
        sa.ForeignKeyConstraint(
            ["report_id"],
            ["report.report_id"],
            name=op.f("fk_report_role_ledger_report_id_report"),
        ),
        sa.ForeignKeyConstraint(
            ["role"],
            ["report_role.role"],
            name=op.f("fk_report_role_ledger_role_report_role"),
        ),
        sa.ForeignKeyConstraint(
            ["set_by_user_id"],
            ["app_user.user_id"],
            name=op.f("fk_report_role_ledger_set_by_user_id_app_user"),
        ),
        sa.PrimaryKeyConstraint(
            "report_id",
            "granted_to_user_id",
            "set_at",
            name=op.f("pk_report_role_ledger"),
        ),
    )
    op.create_table(
        "report_visibility",
        sa.Column("report_id", sa.UUID(), nullable=False),
        sa.Column("set_by_user_id", sa.UUID(), nullable=False),
        sa.Column("public", sa.Boolean(), nullable=False),
        sa.Column(
            "set_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["report_id"],
            ["report.report_id"],
            name=op.f("fk_report_visibility_report_id_report"),
        ),
        sa.ForeignKeyConstraint(
            ["set_by_user_id"],
            ["app_user.user_id"],
            name=op.f("fk_report_visibility_set_by_user_id_app_user"),
        ),
        sa.PrimaryKeyConstraint(
            "report_id", "set_at", name=op.f("pk_report_visibility")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("report_visibility")
    op.drop_table("report_role_ledger")
    op.drop_table("report_role")
    op.drop_table("report")
    # ### end Alembic commands ###
