"""content_blocks_stores_and_mounts

Revision ID: a09066d30034
Revises: ba8207091fd0
Create Date: 2026-09-05 18:25:24.996548

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a09066d30034"
down_revision: str | Sequence[str] | None = "ba8207091fd0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "blob_store",
        sa.Column(
            "blob_id", sa.BigInteger(), sa.Identity(always=False), nullable=False
        ),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "type",
            postgresql.ENUM("chart", "dataset", name="blob_type", metadata=MetaData()),
            nullable=False,
        ),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "content_last_modified_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.CheckConstraint(
            "size_bytes >= 0", name=op.f("ck_blob_store_size_bytes_non_negative")
        ),
        sa.PrimaryKeyConstraint("blob_id", name=op.f("pk_blob_store")),
    )
    op.create_table(
        "text_store",
        sa.Column(
            "text_id", sa.BigInteger(), sa.Identity(always=False), nullable=False
        ),
        sa.Column("payload", sa.Text(), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "content_last_modified_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.CheckConstraint(
            "size_bytes >= 0", name=op.f("ck_text_store_size_bytes_non_negative")
        ),
        sa.PrimaryKeyConstraint("text_id", name=op.f("pk_text_store")),
    )
    op.create_table(
        "content_container",
        sa.Column(
            "container_id", sa.BigInteger(), sa.Identity(always=False), nullable=False
        ),
        sa.Column("chart_id", sa.BigInteger(), nullable=False),
        sa.Column("prose_id", sa.BigInteger(), nullable=False),
        sa.Column("dataset_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.CheckConstraint(
            "chart_id <> dataset_id",
            name=op.f("ck_content_container_chart_and_dataset_distinct"),
        ),
        sa.ForeignKeyConstraint(
            ["chart_id"],
            ["blob_store.blob_id"],
            name=op.f("fk_content_container_chart_id_blob_store"),
        ),
        sa.ForeignKeyConstraint(
            ["dataset_id"],
            ["blob_store.blob_id"],
            name=op.f("fk_content_container_dataset_id_blob_store"),
        ),
        sa.ForeignKeyConstraint(
            ["prose_id"],
            ["text_store.text_id"],
            name=op.f("fk_content_container_prose_id_text_store"),
        ),
        sa.PrimaryKeyConstraint("container_id", name=op.f("pk_content_container")),
    )
    op.create_table(
        "content_mount",
        sa.Column("container_id", sa.BigInteger(), nullable=False),
        sa.Column("report_id", sa.UUID(), nullable=False),
        sa.Column("position", sa.BigInteger(), nullable=True),
        sa.CheckConstraint(
            "position >= 0", name=op.f("ck_content_mount_position_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["container_id"],
            ["content_container.container_id"],
            name=op.f("fk_content_mount_container_id_content_container"),
        ),
        sa.ForeignKeyConstraint(
            ["report_id"],
            ["report.report_id"],
            name=op.f("fk_content_mount_report_id_report"),
        ),
        sa.PrimaryKeyConstraint("container_id", name=op.f("pk_content_mount")),
        sa.UniqueConstraint(
            "report_id",
            "position",
            deferrable=True,
            initially="DEFERRED",
            name=op.f("uq_content_mount_report_id_position"),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("content_mount")
    op.drop_table("content_container")
    op.drop_table("text_store")
    op.drop_table("blob_store")
    # ### end Alembic commands ###
