"""clock timestamp defaults

Swaps every row-timestamp default from `now()` to `clock_timestamp()`.

`now()` is transaction START time and is constant for the whole transaction, so
every row written in one transaction shared a timestamp to the microsecond. The
ledger tables key on `(subject, set_at)`, which made that a primary key
collision: two writes to one report's history in a single transaction were
impossible. See `src.db.schema.write_timestamp` for the full rationale.

Hand written, not autogenerated: `compare_server_default` is deliberately off in
`env.py`, so this difference is invisible to autogenerate.

Rewrites no rows. `SET DEFAULT` only changes what later inserts are given, so
existing timestamps keep whatever they were stamped with.

Revision ID: 90b98c9eccc3
Revises: 4cdf6b05fe38
Create Date: 2026-09-13 11:23:22.666965

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "90b98c9eccc3"
down_revision: str | Sequence[str] | None = "4cdf6b05fe38"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# Every column carrying a "when was this row written" default. Kept in step by
# hand with `src.db.schema`, since nothing compares them automatically.
TIMESTAMP_COLUMNS: tuple[tuple[str, str], ...] = (
    ("app_user", "created_at"),
    ("blob_store", "created_at"),
    ("blob_store", "content_last_modified_at"),
    ("report", "created_at"),
    ("report", "content_last_modified_at"),
    ("text_store", "created_at"),
    ("text_store", "content_last_modified_at"),
    ("content_container", "created_at"),
    ("platform_role_ledger", "set_at"),
    ("report_role_ledger", "set_at"),
    ("report_visibility", "set_at"),
)


def _set_default(expression: str) -> None:
    """Point every timestamp column's default at `expression`."""

    for table, column in TIMESTAMP_COLUMNS:
        op.alter_column(
            table,
            column,
            server_default=sa.text(expression),
            existing_type=postgresql.TIMESTAMP(timezone=True),
            existing_nullable=False,
        )


def upgrade() -> None:
    """Upgrade schema."""
    _set_default("clock_timestamp()")


def downgrade() -> None:
    """Downgrade schema."""
    # Restores the collision described above. Reversible, not advisable.
    _set_default("now()")
