"""app_user and platform roles

Revision ID: 2f07ec09edfe
Revises:
Create Date: 2026-09-05 13:05:06.627093

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "2f07ec09edfe"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app_user",
        sa.Column(
            "user_id", sa.UUID(), server_default=sa.text("uuidv7()"), nullable=False
        ),
        sa.Column("auth0_subject", sa.Text(), nullable=False),
        sa.Column("display_name", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_app_user")),
        sa.UniqueConstraint("auth0_subject", name=op.f("uq_app_user_auth0_subject")),
    )
    op.create_table(
        "platform_role",
        sa.Column("role", sa.Text(), nullable=False),
        sa.Column("precedence", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "precedence > 0", name=op.f("ck_platform_role_precedence_positive")
        ),
        sa.PrimaryKeyConstraint("role", name=op.f("pk_platform_role")),
        sa.UniqueConstraint("precedence", name=op.f("uq_platform_role_precedence")),
    )
    op.create_table(
        "platform_role_ledger",
        sa.Column("granted_to_user_id", sa.UUID(), nullable=False),
        sa.Column("set_by_user_id", sa.UUID(), nullable=False),
        sa.Column("role", sa.Text(), nullable=False),
        sa.Column(
            "set_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["granted_to_user_id"],
            ["app_user.user_id"],
            name=op.f("fk_platform_role_ledger_granted_to_user_id_app_user"),
        ),
        sa.ForeignKeyConstraint(
            ["role"],
            ["platform_role.role"],
            name=op.f("fk_platform_role_ledger_role_platform_role"),
        ),
        sa.ForeignKeyConstraint(
            ["set_by_user_id"],
            ["app_user.user_id"],
            name=op.f("fk_platform_role_ledger_set_by_user_id_app_user"),
        ),
        sa.PrimaryKeyConstraint(
            "granted_to_user_id", "set_at", name=op.f("pk_platform_role_ledger")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("platform_role_ledger")
    op.drop_table("platform_role")
    op.drop_table("app_user")
    # ### end Alembic commands ###
