from src.loaders import ExternalAPI

LOADERS_CONSTANTS_PATH: str = "src.loaders.constants."
BASE_URL_DISPATCH: str = f"{LOADERS_CONSTANTS_PATH}BASE_URL"
NORMALISER_DISPATCH: str = f"{LOADERS_CONSTANTS_PATH}NORMALISER"
FMP_API: ExternalAPI = "FMP"
