/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create New Report
         * @description Open an empty report owned by the caller and private to them.
         *
         *     Nothing is returned but the `Location` of the new report, which is all the
         *     frontend needs to navigate to it.
         */
        post: operations["create_new_report"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/previews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Report Previews */
        get: operations["get_report_previews"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/{report_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Specific Report
         * @description Read one report in full: its metadata and every container mounted in it.
         *
         *     A report that does not exist, or that this caller may not read, never
         *     reaches this body. The guard above answers both.
         */
        get: operations["get_specific_report"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/{report_id}/contents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Generated Content To Report */
        post: operations["add_generated_content_to_report"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/{report_id}/title": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Rename Specific Report
         * @description Retitle a report.
         *
         *     A 204 is enough to confirm it: the caller already knows the title it sent,
         *     so returning the report again would only waste bandwidth.
         */
        put: operations["rename_specific_report"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/{report_id}/visibility": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Publish Or Unpublish Report
         * @description Publish a report to everyone, or take it private again.
         *
         *     The caller is recorded alongside the flip: `report_visibility` is an
         *     append-only history, and who published a report is part of what it answers.
         */
        put: operations["publish_or_unpublish_report"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Axis */
        Axis: {
            /** Data */
            data?: unknown[] | null;
            /**
             * Type
             * @enum {string}
             */
            type: "value" | "category" | "time" | "log";
        };
        ByteField: number;
        /** ChartConfigModel */
        ChartConfigModel: {
            /**
             * Dataset
             * @default []
             */
            dataset: components["schemas"]["Dataset"][];
            /**
             * @default {
             *       "data": []
             *     }
             */
            legend: components["schemas"]["Legend"];
            /**
             * Series
             * @default []
             */
            series: components["schemas"]["Series"][];
            /**
             * @default {
             *       "text": ""
             *     }
             */
            title: components["schemas"]["Title"];
            /**
             * @default {
             *       "trigger": "item"
             *     }
             */
            tooltip: components["schemas"]["Tooltip"];
            /**
             * Xaxis
             * @default []
             */
            xAxis: components["schemas"]["Axis"][];
            /**
             * Yaxis
             * @default []
             */
            yAxis: components["schemas"]["Axis"][];
        };
        ColumnarDataset: {
            [key: string]: unknown[];
        };
        /** Dataset */
        Dataset: {
            /** @default {} */
            source: components["schemas"]["DatasetType"];
        };
        DatasetType: components["schemas"]["RowObjectDataset"] | components["schemas"]["ColumnarDataset"];
        /** DisplayedContentContainer */
        DisplayedContentContainer: {
            chart: components["schemas"]["ChartConfigModel"] | null;
            /**
             * Container Id
             * Format: uuid
             */
            container_id: string;
            /** Prose */
            prose: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        HexColor: string;
        /** ItemStyle */
        ItemStyle: {
            /**
             * Color
             * @default #000
             */
            color: components["schemas"]["RGBA"] | components["schemas"]["HexColor"];
        };
        /** Legend */
        Legend: {
            /**
             * Data
             * @default []
             */
            data: unknown[];
        };
        /** LineStyle */
        LineStyle: {
            /**
             * Cap
             * @default butt
             * @enum {string}
             */
            cap: "butt" | "round" | "square";
            /**
             * Color
             * @default #000
             */
            color: components["schemas"]["RGBA"] | components["schemas"]["HexColor"];
            /** @default 0 */
            dashOffset: components["schemas"]["NonNegativeNumberField"];
            /**
             * Join
             * @default bevel
             * @enum {string}
             */
            join: "bevel" | "round" | "miter";
            /**
             * Type
             * @default solid
             * @enum {string}
             */
            type: "solid" | "dashed" | "dotted";
            /** @default 2 */
            width: components["schemas"]["NonNegativeNumberField"];
        };
        MinimumReportRole: components["schemas"]["ReportRoleName"];
        NonEmptyString: string;
        NonNegativeInt: number;
        NonNegativeNumberField: components["schemas"]["Number"];
        NormalisedFloatField: number;
        Number: number;
        Params: {
            [key: string]: unknown;
        };
        /** PromptBody */
        PromptBody: {
            /** Prompt */
            prompt: string;
        };
        /** RGBA */
        RGBA: {
            /** @default 1 */
            alpha: components["schemas"]["NormalisedFloatField"];
            /** @default 0 */
            blue: components["schemas"]["ByteField"];
            /** @default 0 */
            green: components["schemas"]["ByteField"];
            /** @default 0 */
            red: components["schemas"]["ByteField"];
        };
        /** ReportFull */
        ReportFull: {
            /** Authors */
            authors: components["schemas"]["NonEmptyString"][];
            /** Content Containers */
            content_containers: components["schemas"]["DisplayedContentContainer"][];
            /** Public */
            public: boolean;
            title: components["schemas"]["NonEmptyString"];
        };
        /** ReportPreview */
        ReportPreview: {
            /** Authors */
            authors: components["schemas"]["NonEmptyString"][];
            chart: components["schemas"]["ChartConfigModel"];
            title: components["schemas"]["NonEmptyString"];
        };
        /** @enum {string} */
        ReportRoleName: "viewer" | "commenter" | "editor" | "owner";
        /** ReportTitle */
        ReportTitle: {
            title: components["schemas"]["NonEmptyString"];
        };
        /** ReportVisibility */
        ReportVisibility: {
            /** Public */
            public: boolean;
        };
        RowObjectDataset: components["schemas"]["Params"][];
        /** Series */
        Series: {
            /** Data */
            data?: unknown[] | null;
            /** Encode */
            encode?: {
                [key: string]: unknown;
            } | null;
            /**
             * @default {
             *       "color": "#000"
             *     }
             */
            itemStyle: components["schemas"]["ItemStyle"];
            /**
             * @default {
             *       "cap": "butt",
             *       "color": "#000",
             *       "dashOffset": 0,
             *       "join": "bevel",
             *       "type": "solid",
             *       "width": 2
             *     }
             */
            lineStyle: components["schemas"]["LineStyle"];
            /**
             * Name
             * @default
             */
            name: string;
            /**
             * Showsymbol
             * @default true
             */
            showSymbol: boolean;
            type: components["schemas"]["SeriesType"];
            /**
             * Yaxisindex
             * @default 0
             */
            yAxisIndex: number;
        };
        /** @enum {string} */
        SeriesType: "line" | "bar" | "pie" | "scatter" | "effectScatter" | "radar" | "tree" | "treemap" | "sunburst" | "boxplot" | "candlestick" | "heatmap" | "map" | "parallel" | "lines" | "graph" | "sankey" | "funnel" | "gauge" | "pictorialBar" | "themeRiver" | "chord" | "custom";
        /** Title */
        Title: {
            /**
             * Text
             * @default
             */
            text: string;
        };
        /** Tooltip */
        Tooltip: {
            /**
             * Trigger
             * @default item
             * @enum {string}
             */
            trigger: "item" | "axis" | "none";
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    create_new_report: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    /** @description Where the newly created report can be found. */
                    Location?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_report_previews: {
        parameters: {
            query?: {
                public?: boolean | null;
                minimum_report_role?: components["schemas"]["MinimumReportRole"] | null;
                cursor?: string | null;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportPreview"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_specific_report: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportFull"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_generated_content_to_report: {
        parameters: {
            query?: {
                position?: components["schemas"]["NonNegativeInt"] | null;
            };
            header?: never;
            path: {
                report_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PromptBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DisplayedContentContainer"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rename_specific_report: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReportTitle"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    publish_or_unpublish_report: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                report_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReportVisibility"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
