name: Deploy to development
# Adapted from https://developer.hashicorp.com/terraform/tutorials/automation/github-actions

on:
  pull_request:
    branches:
      - main

env:
  TF_API_TOKEN: "${{ secrets.TF_API_TOKEN }}"
  TF_CLOUD_ORGANIZATION: "${{ vars.TF_CLOUD_ORGANIZATION }}"
  BOT_NAME: Bot
  PR_NUMBER: "${{ github.event.pull_request.number }}"
  TF_WORKSPACE_DEVELOPMENT_PR: "${{ vars.TF_WORKSPACE_DEV_PREFIX }}${{ github.event.pull_request.number }}"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}

jobs:
  reconcile-ephemeral-workspaces:
    uses: ./.github/workflows/reconcile-workspaces.yml
    secrets: inherit
    with:
      pull_request_number: ${{ github.event.pull_request.number }}

  # deploy-development-shared:
  #   runs-on: ubuntu-latest
  #   permissions:
  #     contents: read
  #     pull-requests: write

  deploy-development-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    needs: reconcile-ephemeral-workspaces

    steps:
      - uses: actions/checkout@v7

      - name: Upload configuration
        uses: hashicorp/tfc-workflows-github/actions/upload-configuration@v1.3.2
        id: apply-upload
        with:
          workspace: ${{ env.TF_WORKSPACE_DEVELOPMENT_PR }}
          directory: ${{ vars.TF_DIRECTORY_INFRASTRUCTURE }}

      - name: Create apply run
        uses: hashicorp/tfc-workflows-github/actions/create-run@v1.3.2
        id: apply-run
        with:
          workspace: ${{ env.TF_WORKSPACE_DEVELOPMENT_PR }}
          configuration_version: ${{ steps.apply-upload.outputs.configuration_version_id }}

      - name: Apply
        uses: hashicorp/tfc-workflows-github/actions/apply-run@v1.3.2
        if: fromJSON(steps.apply-run.outputs.payload).data.attributes.actions.IsConfirmable
        id: apply
        with:
          run: ${{ steps.apply-run.outputs.run_id }}

      - name: Update PR
        uses: actions/github-script@v9
        id: plan-comment
        env:
          PR_NUMBER: ${{ env.PR_NUMBER }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `#### HCP Terraform Plan application to Development: ${{ steps.apply.conclusion }}
            [HCP Terraform Apply](${{ steps.apply-run.outputs.run_link }})
            `;

            await github.rest.issues.createComment({
              issue_number: Number(process.env.PR_NUMBER),
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            });
